## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_Vacation.csv")
vacation_df.head()


City_ID        City Country  Max Temp Current Description      Lat  \
0        1      Atuona      PF     78.48           clear sky  -9.8000   
1        3  Champerico      GT     84.31     overcast clouds  14.3000   
2        5         Soe      ID     85.05    scattered clouds  -9.8607   
3        6        Atar      MR     85.42     overcast clouds  20.5169   
4        8  Georgetown      MY     89.53          few clouds   5.4112   

        Lng                         Hotel Name  
0 -139.0333                        Villa Enata  
1  -91.9167  Hotel y restaurante "El Diamante"  
2  124.2840                         Dena Hotel  
3  -13.0499                     Oumou Elghoura  
4  100.3354                     Cititel Penang

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [22]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 4b. Display the figure
fig



Figure(layout=FigureLayout(height='420px'))

In [33]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Lovington')
                                & (vacation_df['Hotel Name']=='Buena vida rv parks')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Lovington')
                              & (vacation_df['Hotel Name']=='Buena vida rv parks')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='San Patricio')
                              & (vacation_df['Hotel Name']=='Motel 6 Sinton, TX')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Galveston')
                                & (vacation_df['Hotel Name']=='Crystal Suites')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Rincon')
                                & (vacation_df['Hotel Name']=='Days Inn Rincon')]

In [34]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()

start, stop1, stop2, stop3


(array([[  32.944 , -103.3485]]),
 array([[ 28.017 , -97.5169]]),
 array([[ 29.3669, -94.9669]]),
 array([[ 32.296 , -81.2354]]))

In [35]:
# Latitude - Longitude pairs
start=(32.944 , -103.3485)
end=(32.944 , -103.3485)
stop1=(28.017 , -97.5169)
stop2=(29.3669, -94.9669)
stop3=(32.296 , -81.2354)


In [36]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING")

fig.add_layer(itinerary_trip_plan)
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID          City Country  Max Temp Current Description      Lat  \
0      655     Lovington      US     81.45       broken clouds  32.9440   
1       97  San Patricio      US     78.85    scattered clouds  28.0170   
2      696     Galveston      US     80.56           clear sky  29.3669   
3      560        Rincon      US     76.96           clear sky  32.2960   

        Lng           Hotel Name  
0 -103.3485  Buena vida rv parks  
1  -97.5169   Motel 6 Sinton, TX  
2  -94.9669       Crystal Suites  
3  -81.2354      Days Inn Rincon

In [40]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
itinerry_locations = itinerary_df[["Lat", "Lng"]]

In [41]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(36.0, -76.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=itinerary_info)
fig.add_layer(marker_layer)


# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))